"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { Language } from "./types";

/**
 * UI translation.
 *
 * Interface strings are translated here at build time. Assistant *answers* are a separate
 * concern: those are generated in the requested language by the backend, because
 * translating regulatory guidance with a lookup table would be unsafe.
 *
 * Adding a language means adding one entry to `DICTIONARIES` and one to `LANGUAGES`;
 * nothing else in the app needs to change.
 */

export const LANGUAGES: { code: Language; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिंदी" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
];

const en = {
  "nav.home": "Home",
  "nav.standards": "Standards",
  "nav.certification": "Certification",
  "nav.labs": "Testing Labs",
  "nav.hallmarking": "Hallmarking",
  "nav.consumer": "Consumer Help",
  "nav.about": "About",
  "nav.askAi": "Ask AI",
  "nav.login": "Login",
  "nav.admin": "Admin",
  "nav.logout": "Log out",

  "hero.title": "Your Intelligent Assistant for Indian Standards & BIS Services",
  "hero.subtitle":
    "Find standards, understand certification requirements, discover testing laboratories, and get trusted answers from BIS knowledge sources — in simple language.",
  "hero.placeholder": "Describe your product or ask a question…",
  "hero.search": "Ask",
  "hero.voice": "Voice input",
  "hero.tryAsking": "Try asking",

  "common.loading": "Working…",
  "common.error": "Something went wrong",
  "common.retry": "Try again",
  "common.search": "Search",
  "common.filters": "Filters",
  "common.clear": "Clear",
  "common.results": "results",
  "common.noResults": "No results found",
  "common.viewSource": "View source",
  "common.sources": "Sources",
  "common.close": "Close",
  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.demoData": "Demo data",
  "common.all": "All",
  "common.page": "Page",
  "common.clause": "Clause",

  "answer.heading": "Answer",
  "answer.productUnderstanding": "Product Understanding",
  "answer.applicableStandards": "Potentially Applicable Standards",
  "answer.whyMatch": "Why these standards match",
  "answer.certification": "Certification Requirement",
  "answer.testing": "Testing Requirements",
  "answer.documents": "Required Documents",
  "answer.nextSteps": "Recommended Next Steps",
  "answer.sources": "Sources",
  "answer.confidence": "Confidence",
  "answer.verified": "AI Answer • Source Verified",
  "answer.unverified": "AI Answer • Unverified",
  "answer.relevance": "Relevance",
  "answer.whyRecommended": "Why was this standard recommended?",
  "answer.guardrails": "Evidence & guardrail notes",
  "answer.noEvidence": "I couldn't find enough verified information to answer this confidently.",
  "answer.generatedBy": "Generated by",

  "confidence.high": "High Confidence",
  "confidence.medium": "Medium Confidence",
  "confidence.low": "Low Confidence",
  "confidence.note":
    "This is the AI system's evidence-confidence indicator based on retrieval quality. It is not an official BIS rating.",

  "assistant.title": "BIS AI Assistant",
  "assistant.newChat": "New Chat",
  "assistant.recent": "Recent Chats",
  "assistant.saved": "Saved Answers",
  "assistant.placeholder": "Ask about standards, certification, testing or hallmarking…",
  "assistant.send": "Send",
  "assistant.emptyTitle": "What would you like to know?",
  "assistant.emptyBody":
    "Ask in your own words. Every technical answer is checked against the indexed BIS knowledge base before it is shown.",
  "assistant.save": "Save answer",
  "assistant.saved.done": "Saved",

  "pipeline.intent": "Understanding the question",
  "pipeline.product": "Extracting the product profile",
  "pipeline.retrieving": "Searching the BIS knowledge base",
  "pipeline.retrieved": "Evidence retrieved",
  "pipeline.ranked": "Ranking applicable standards",
  "pipeline.composing": "Composing the answer",
  "pipeline.verified": "Verifying sources",

  "recommend.title": "Find Applicable Standards",
  "recommend.subtitle":
    "Describe what you make. The assistant extracts a product profile, searches the indexed BIS corpus, and explains why each standard matched.",
  "recommend.placeholder":
    "Describe your product… e.g. I manufacture stainless steel lunch boxes for school children.",
  "recommend.submit": "Find standards",
  "recommend.disclaimer":
    "Applicability should be verified against the complete product specifications and current BIS requirements.",

  "standards.title": "Indian Standards",
  "standards.subtitle": "Search the indexed catalogue by number, product, industry or keyword.",
  "standards.placeholder": "IS number, product name, industry or keyword…",
  "standards.status": "Status",
  "standards.industry": "Industry",
  "standards.category": "Category",
  "standards.year": "Year",
  "standards.compare": "Compare",
  "standards.compareSelected": "Compare selected",
  "standards.scope": "Scope",
  "standards.edition": "Edition",
  "standards.related": "Related standards",
  "standards.selectToCompare": "Select two or more standards to compare",

  "compare.title": "Compare Standards",
  "compare.subtitle": "All values are drawn from the indexed knowledge base.",
  "compare.parameter": "Parameter",
  "compare.add": "Add a standard",

  "certification.title": "BIS Certification Assistant",
  "certification.subtitle":
    "A step-by-step path from identifying your product to holding a licence.",
  "certification.describe": "Describe your product or enter a standard number",
  "certification.analyze": "Analyse",
  "certification.generateChecklist": "Generate Compliance Checklist",
  "certification.documents": "Required documents",
  "certification.notes": "Important notes",
  "certification.schemes": "Certification schemes",

  "checklist.title": "Product Compliance Checklist",
  "checklist.subtitle": "Track your progress towards certification.",
  "checklist.completed": "completed",
  "checklist.generate": "Generate checklist",
  "checklist.product": "Product",
  "checklist.reset": "Reset progress",

  "labs.title": "Find a Testing Laboratory",
  "labs.subtitle": "Filter recognised laboratories by product, standard, test type and location.",
  "labs.state": "State",
  "labs.city": "City",
  "labs.testType": "Test type",
  "labs.standard": "Standard",
  "labs.category": "Product category",
  "labs.capabilities": "Testing capabilities",
  "labs.scope": "Recognised scope",
  "labs.recognition": "Recognition status",
  "labs.contact": "Contact",
  "labs.noFabrication":
    "Laboratory records shown here come only from the loaded dataset. Nothing on this page is generated by the AI.",

  "hallmarking.title": "Hallmarking Assistant",
  "hallmarking.subtitle": "Gold, silver, HUID, hallmarking centres and consumer verification.",
  "hallmarking.ask": "Ask about hallmarking…",

  "consumer.title": "BIS Consumer Assistant",
  "consumer.subtitle": "Plain-language help with marks, verification, safety and complaints.",
  "consumer.ask": "Ask in simple words…",

  "admin.title": "Knowledge Base Administration",
  "admin.totalStandards": "Total Standards",
  "admin.indexedDocuments": "Indexed Documents",
  "admin.indexedChunks": "Indexed Chunks",
  "admin.certificationDocs": "Certification Schemes",
  "admin.labRecords": "Laboratory Records",
  "admin.hallmarkingDocs": "Hallmarking Topics",
  "admin.lastUpdate": "Last Knowledge Update",
  "admin.upload": "Upload BIS document",
  "admin.uploadHint": "PDF, TXT or Markdown, up to 40 MB. The document is chunked and indexed immediately.",
  "admin.documents": "Documents",
  "admin.failed": "Failed / partial documents",
  "admin.queries": "Query log",
  "admin.quality": "Retrieval quality",
  "admin.reindex": "Rebuild index",
  "admin.remove": "Remove",
  "admin.signInRequired": "Sign in with an administrator account to manage the knowledge base.",

  "login.title": "Sign in",
  "login.subtitle": "Administrator access is required for knowledge base management.",
  "login.username": "Username",
  "login.password": "Password",
  "login.submit": "Sign in",
  "login.demoCredentials": "Demo credentials",

  "about.title": "About this assistant",

  "demo.banner":
    "Demo data — replace with authorized BIS data before production. The records loaded here are illustrative, not an official BIS extract.",
  "footer.disclaimer":
    "This is an AI decision-support prototype. It does not issue certifications and is not an official BIS service. Always verify against official BIS sources.",
} as const;

export type TranslationKey = keyof typeof en;

const hi: Record<TranslationKey, string> = {
  "nav.home": "होम",
  "nav.standards": "मानक",
  "nav.certification": "प्रमाणन",
  "nav.labs": "परीक्षण प्रयोगशालाएँ",
  "nav.hallmarking": "हॉलमार्किंग",
  "nav.consumer": "उपभोक्ता सहायता",
  "nav.about": "परिचय",
  "nav.askAi": "AI से पूछें",
  "nav.login": "लॉग इन",
  "nav.admin": "प्रशासन",
  "nav.logout": "लॉग आउट",

  "hero.title": "भारतीय मानकों और BIS सेवाओं के लिए आपका बुद्धिमान सहायक",
  "hero.subtitle":
    "मानक खोजें, प्रमाणन आवश्यकताएँ समझें, परीक्षण प्रयोगशालाएँ ढूँढें और BIS ज्ञान स्रोतों से विश्वसनीय उत्तर पाएँ — सरल भाषा में।",
  "hero.placeholder": "अपने उत्पाद का विवरण दें या प्रश्न पूछें…",
  "hero.search": "पूछें",
  "hero.voice": "आवाज़ से इनपुट",
  "hero.tryAsking": "यह पूछकर देखें",

  "common.loading": "काम चल रहा है…",
  "common.error": "कुछ गड़बड़ हो गई",
  "common.retry": "पुनः प्रयास करें",
  "common.search": "खोजें",
  "common.filters": "फ़िल्टर",
  "common.clear": "साफ़ करें",
  "common.results": "परिणाम",
  "common.noResults": "कोई परिणाम नहीं मिला",
  "common.viewSource": "स्रोत देखें",
  "common.sources": "स्रोत",
  "common.close": "बंद करें",
  "common.copy": "कॉपी",
  "common.copied": "कॉपी हो गया",
  "common.demoData": "डेमो डेटा",
  "common.all": "सभी",
  "common.page": "पृष्ठ",
  "common.clause": "खंड",

  "answer.heading": "उत्तर",
  "answer.productUnderstanding": "उत्पाद की समझ",
  "answer.applicableStandards": "संभावित रूप से लागू मानक",
  "answer.whyMatch": "ये मानक क्यों मेल खाते हैं",
  "answer.certification": "प्रमाणन आवश्यकता",
  "answer.testing": "परीक्षण आवश्यकताएँ",
  "answer.documents": "आवश्यक दस्तावेज़",
  "answer.nextSteps": "अनुशंसित अगले कदम",
  "answer.sources": "स्रोत",
  "answer.confidence": "विश्वास स्तर",
  "answer.verified": "AI उत्तर • स्रोत सत्यापित",
  "answer.unverified": "AI उत्तर • असत्यापित",
  "answer.relevance": "प्रासंगिकता",
  "answer.whyRecommended": "यह मानक क्यों सुझाया गया?",
  "answer.guardrails": "साक्ष्य और सुरक्षा टिप्पणियाँ",
  "answer.noEvidence": "मुझे इसका आत्मविश्वास से उत्तर देने के लिए पर्याप्त सत्यापित जानकारी नहीं मिली।",
  "answer.generatedBy": "द्वारा निर्मित",

  "confidence.high": "उच्च विश्वास",
  "confidence.medium": "मध्यम विश्वास",
  "confidence.low": "निम्न विश्वास",
  "confidence.note":
    "यह पुनर्प्राप्ति गुणवत्ता पर आधारित AI प्रणाली का साक्ष्य-विश्वास संकेतक है। यह आधिकारिक BIS रेटिंग नहीं है।",

  "assistant.title": "BIS AI सहायक",
  "assistant.newChat": "नई चैट",
  "assistant.recent": "हाल की चैट",
  "assistant.saved": "सहेजे गए उत्तर",
  "assistant.placeholder": "मानक, प्रमाणन, परीक्षण या हॉलमार्किंग के बारे में पूछें…",
  "assistant.send": "भेजें",
  "assistant.emptyTitle": "आप क्या जानना चाहेंगे?",
  "assistant.emptyBody":
    "अपने शब्दों में पूछें। हर तकनीकी उत्तर दिखाने से पहले अनुक्रमित BIS ज्ञान आधार से जाँचा जाता है।",
  "assistant.save": "उत्तर सहेजें",
  "assistant.saved.done": "सहेजा गया",

  "pipeline.intent": "प्रश्न को समझा जा रहा है",
  "pipeline.product": "उत्पाद प्रोफ़ाइल निकाली जा रही है",
  "pipeline.retrieving": "BIS ज्ञान आधार खोजा जा रहा है",
  "pipeline.retrieved": "साक्ष्य प्राप्त हुए",
  "pipeline.ranked": "लागू मानकों की रैंकिंग",
  "pipeline.composing": "उत्तर तैयार किया जा रहा है",
  "pipeline.verified": "स्रोतों का सत्यापन",

  "recommend.title": "लागू मानक खोजें",
  "recommend.subtitle":
    "बताएं आप क्या बनाते हैं। सहायक उत्पाद प्रोफ़ाइल निकालता है, BIS संग्रह खोजता है और बताता है कि प्रत्येक मानक क्यों मेल खाया।",
  "recommend.placeholder":
    "अपने उत्पाद का विवरण दें… जैसे मैं स्कूली बच्चों के लिए स्टेनलेस स्टील के लंच बॉक्स बनाता हूँ।",
  "recommend.submit": "मानक खोजें",
  "recommend.disclaimer":
    "लागू होने की पुष्टि पूर्ण उत्पाद विनिर्देशों और वर्तमान BIS आवश्यकताओं के विरुद्ध की जानी चाहिए।",

  "standards.title": "भारतीय मानक",
  "standards.subtitle": "संख्या, उत्पाद, उद्योग या कीवर्ड से अनुक्रमित सूची खोजें।",
  "standards.placeholder": "IS संख्या, उत्पाद नाम, उद्योग या कीवर्ड…",
  "standards.status": "स्थिति",
  "standards.industry": "उद्योग",
  "standards.category": "श्रेणी",
  "standards.year": "वर्ष",
  "standards.compare": "तुलना करें",
  "standards.compareSelected": "चयनित की तुलना करें",
  "standards.scope": "क्षेत्र",
  "standards.edition": "संस्करण",
  "standards.related": "संबंधित मानक",
  "standards.selectToCompare": "तुलना के लिए दो या अधिक मानक चुनें",

  "compare.title": "मानकों की तुलना",
  "compare.subtitle": "सभी मान अनुक्रमित ज्ञान आधार से लिए गए हैं।",
  "compare.parameter": "मापदंड",
  "compare.add": "मानक जोड़ें",

  "certification.title": "BIS प्रमाणन सहायक",
  "certification.subtitle": "उत्पाद की पहचान से लाइसेंस तक चरण-दर-चरण मार्ग।",
  "certification.describe": "अपने उत्पाद का विवरण दें या मानक संख्या दर्ज करें",
  "certification.analyze": "विश्लेषण करें",
  "certification.generateChecklist": "अनुपालन चेकलिस्ट बनाएँ",
  "certification.documents": "आवश्यक दस्तावेज़",
  "certification.notes": "महत्वपूर्ण टिप्पणियाँ",
  "certification.schemes": "प्रमाणन योजनाएँ",

  "checklist.title": "उत्पाद अनुपालन चेकलिस्ट",
  "checklist.subtitle": "प्रमाणन की दिशा में अपनी प्रगति देखें।",
  "checklist.completed": "पूर्ण",
  "checklist.generate": "चेकलिस्ट बनाएँ",
  "checklist.product": "उत्पाद",
  "checklist.reset": "प्रगति रीसेट करें",

  "labs.title": "परीक्षण प्रयोगशाला खोजें",
  "labs.subtitle": "उत्पाद, मानक, परीक्षण प्रकार और स्थान के अनुसार मान्यता प्राप्त प्रयोगशालाएँ छाँटें।",
  "labs.state": "राज्य",
  "labs.city": "शहर",
  "labs.testType": "परीक्षण प्रकार",
  "labs.standard": "मानक",
  "labs.category": "उत्पाद श्रेणी",
  "labs.capabilities": "परीक्षण क्षमताएँ",
  "labs.scope": "मान्यता प्राप्त क्षेत्र",
  "labs.recognition": "मान्यता स्थिति",
  "labs.contact": "संपर्क",
  "labs.noFabrication":
    "यहाँ दिखाए गए प्रयोगशाला रिकॉर्ड केवल लोड किए गए डेटासेट से हैं। इस पृष्ठ पर कुछ भी AI द्वारा उत्पन्न नहीं है।",

  "hallmarking.title": "हॉलमार्किंग सहायक",
  "hallmarking.subtitle": "सोना, चाँदी, HUID, हॉलमार्किंग केंद्र और उपभोक्ता सत्यापन।",
  "hallmarking.ask": "हॉलमार्किंग के बारे में पूछें…",

  "consumer.title": "BIS उपभोक्ता सहायक",
  "consumer.subtitle": "चिह्न, सत्यापन, सुरक्षा और शिकायतों पर सरल भाषा में सहायता।",
  "consumer.ask": "सरल शब्दों में पूछें…",

  "admin.title": "ज्ञान आधार प्रशासन",
  "admin.totalStandards": "कुल मानक",
  "admin.indexedDocuments": "अनुक्रमित दस्तावेज़",
  "admin.indexedChunks": "अनुक्रमित खंड",
  "admin.certificationDocs": "प्रमाणन योजनाएँ",
  "admin.labRecords": "प्रयोगशाला रिकॉर्ड",
  "admin.hallmarkingDocs": "हॉलमार्किंग विषय",
  "admin.lastUpdate": "अंतिम ज्ञान अद्यतन",
  "admin.upload": "BIS दस्तावेज़ अपलोड करें",
  "admin.uploadHint": "PDF, TXT या Markdown, 40 MB तक। दस्तावेज़ तुरंत अनुक्रमित किया जाता है।",
  "admin.documents": "दस्तावेज़",
  "admin.failed": "विफल / आंशिक दस्तावेज़",
  "admin.queries": "प्रश्न लॉग",
  "admin.quality": "पुनर्प्राप्ति गुणवत्ता",
  "admin.reindex": "इंडेक्स पुनर्निर्माण",
  "admin.remove": "हटाएँ",
  "admin.signInRequired": "ज्ञान आधार प्रबंधन के लिए प्रशासक खाते से साइन इन करें।",

  "login.title": "साइन इन",
  "login.subtitle": "ज्ञान आधार प्रबंधन के लिए प्रशासक पहुँच आवश्यक है।",
  "login.username": "उपयोगकर्ता नाम",
  "login.password": "पासवर्ड",
  "login.submit": "साइन इन",
  "login.demoCredentials": "डेमो क्रेडेंशियल",

  "about.title": "इस सहायक के बारे में",

  "demo.banner":
    "डेमो डेटा — उत्पादन से पहले अधिकृत BIS डेटा से बदलें। यहाँ लोड किए गए रिकॉर्ड उदाहरण मात्र हैं, आधिकारिक BIS उद्धरण नहीं।",
  "footer.disclaimer":
    "यह एक AI निर्णय-सहायता प्रोटोटाइप है। यह प्रमाणन जारी नहीं करता और आधिकारिक BIS सेवा नहीं है। हमेशा आधिकारिक BIS स्रोतों से पुष्टि करें।",
};

const bn: Record<TranslationKey, string> = {
  "nav.home": "হোম",
  "nav.standards": "মান",
  "nav.certification": "সার্টিফিকেশন",
  "nav.labs": "পরীক্ষাগার",
  "nav.hallmarking": "হলমার্কিং",
  "nav.consumer": "ভোক্তা সহায়তা",
  "nav.about": "পরিচিতি",
  "nav.askAi": "AI-কে জিজ্ঞাসা করুন",
  "nav.login": "লগ ইন",
  "nav.admin": "প্রশাসন",
  "nav.logout": "লগ আউট",

  "hero.title": "ভারতীয় মান ও BIS পরিষেবার জন্য আপনার বুদ্ধিমান সহকারী",
  "hero.subtitle":
    "মান খুঁজুন, সার্টিফিকেশনের শর্ত বুঝুন, পরীক্ষাগার খুঁজে নিন এবং BIS জ্ঞানভাণ্ডার থেকে নির্ভরযোগ্য উত্তর পান — সহজ ভাষায়।",
  "hero.placeholder": "আপনার পণ্যের বর্ণনা দিন বা প্রশ্ন করুন…",
  "hero.search": "জিজ্ঞাসা করুন",
  "hero.voice": "ভয়েস ইনপুট",
  "hero.tryAsking": "জিজ্ঞাসা করে দেখুন",

  "common.loading": "কাজ চলছে…",
  "common.error": "কিছু একটা ভুল হয়েছে",
  "common.retry": "আবার চেষ্টা করুন",
  "common.search": "খুঁজুন",
  "common.filters": "ফিল্টার",
  "common.clear": "মুছুন",
  "common.results": "ফলাফল",
  "common.noResults": "কোনো ফলাফল পাওয়া যায়নি",
  "common.viewSource": "উৎস দেখুন",
  "common.sources": "উৎস",
  "common.close": "বন্ধ করুন",
  "common.copy": "কপি",
  "common.copied": "কপি হয়েছে",
  "common.demoData": "ডেমো ডেটা",
  "common.all": "সব",
  "common.page": "পৃষ্ঠা",
  "common.clause": "ধারা",

  "answer.heading": "উত্তর",
  "answer.productUnderstanding": "পণ্য সম্পর্কে বোঝাপড়া",
  "answer.applicableStandards": "সম্ভাব্য প্রযোজ্য মান",
  "answer.whyMatch": "কেন এই মানগুলি মিলেছে",
  "answer.certification": "সার্টিফিকেশনের প্রয়োজনীয়তা",
  "answer.testing": "পরীক্ষার প্রয়োজনীয়তা",
  "answer.documents": "প্রয়োজনীয় নথি",
  "answer.nextSteps": "পরবর্তী প্রস্তাবিত পদক্ষেপ",
  "answer.sources": "উৎস",
  "answer.confidence": "আস্থার মাত্রা",
  "answer.verified": "AI উত্তর • উৎস যাচাই করা",
  "answer.unverified": "AI উত্তর • যাচাই করা হয়নি",
  "answer.relevance": "প্রাসঙ্গিকতা",
  "answer.whyRecommended": "কেন এই মানটি সুপারিশ করা হলো?",
  "answer.guardrails": "প্রমাণ ও সুরক্ষা টীকা",
  "answer.noEvidence": "আত্মবিশ্বাসের সঙ্গে উত্তর দেওয়ার মতো যথেষ্ট যাচাইকৃত তথ্য আমি পাইনি।",
  "answer.generatedBy": "তৈরি করেছে",

  "confidence.high": "উচ্চ আস্থা",
  "confidence.medium": "মাঝারি আস্থা",
  "confidence.low": "নিম্ন আস্থা",
  "confidence.note":
    "এটি পুনরুদ্ধারের গুণমানের ভিত্তিতে AI সিস্টেমের প্রমাণ-আস্থা সূচক। এটি কোনো সরকারি BIS রেটিং নয়।",

  "assistant.title": "BIS AI সহকারী",
  "assistant.newChat": "নতুন চ্যাট",
  "assistant.recent": "সাম্প্রতিক চ্যাট",
  "assistant.saved": "সংরক্ষিত উত্তর",
  "assistant.placeholder": "মান, সার্টিফিকেশন, পরীক্ষা বা হলমার্কিং সম্পর্কে জিজ্ঞাসা করুন…",
  "assistant.send": "পাঠান",
  "assistant.emptyTitle": "আপনি কী জানতে চান?",
  "assistant.emptyBody":
    "নিজের ভাষায় জিজ্ঞাসা করুন। প্রতিটি কারিগরি উত্তর দেখানোর আগে সূচিবদ্ধ BIS জ্ঞানভাণ্ডারের সঙ্গে যাচাই করা হয়।",
  "assistant.save": "উত্তর সংরক্ষণ করুন",
  "assistant.saved.done": "সংরক্ষিত",

  "pipeline.intent": "প্রশ্নটি বোঝা হচ্ছে",
  "pipeline.product": "পণ্যের প্রোফাইল বের করা হচ্ছে",
  "pipeline.retrieving": "BIS জ্ঞানভাণ্ডারে খোঁজা হচ্ছে",
  "pipeline.retrieved": "প্রমাণ পাওয়া গেছে",
  "pipeline.ranked": "প্রযোজ্য মান সাজানো হচ্ছে",
  "pipeline.composing": "উত্তর তৈরি হচ্ছে",
  "pipeline.verified": "উৎস যাচাই করা হচ্ছে",

  "recommend.title": "প্রযোজ্য মান খুঁজুন",
  "recommend.subtitle":
    "আপনি কী তৈরি করেন বলুন। সহকারী পণ্যের প্রোফাইল বের করে, BIS সংগ্রহে খোঁজে এবং প্রতিটি মান কেন মিলেছে তা ব্যাখ্যা করে।",
  "recommend.placeholder":
    "আপনার পণ্যের বর্ণনা দিন… যেমন আমি স্কুল শিশুদের জন্য স্টেইনলেস স্টিলের লাঞ্চ বক্স তৈরি করি।",
  "recommend.submit": "মান খুঁজুন",
  "recommend.disclaimer":
    "প্রযোজ্যতা সম্পূর্ণ পণ্য নির্দিষ্টকরণ ও বর্তমান BIS শর্তের সঙ্গে মিলিয়ে যাচাই করা উচিত।",

  "standards.title": "ভারতীয় মান",
  "standards.subtitle": "নম্বর, পণ্য, শিল্প বা কীওয়ার্ড দিয়ে সূচিবদ্ধ তালিকা খুঁজুন।",
  "standards.placeholder": "IS নম্বর, পণ্যের নাম, শিল্প বা কীওয়ার্ড…",
  "standards.status": "অবস্থা",
  "standards.industry": "শিল্প",
  "standards.category": "শ্রেণি",
  "standards.year": "বছর",
  "standards.compare": "তুলনা করুন",
  "standards.compareSelected": "নির্বাচিতগুলি তুলনা করুন",
  "standards.scope": "পরিধি",
  "standards.edition": "সংস্করণ",
  "standards.related": "সম্পর্কিত মান",
  "standards.selectToCompare": "তুলনার জন্য দুই বা তার বেশি মান নির্বাচন করুন",

  "compare.title": "মান তুলনা",
  "compare.subtitle": "সব তথ্য সূচিবদ্ধ জ্ঞানভাণ্ডার থেকে নেওয়া।",
  "compare.parameter": "মাপকাঠি",
  "compare.add": "মান যোগ করুন",

  "certification.title": "BIS সার্টিফিকেশন সহকারী",
  "certification.subtitle": "পণ্য শনাক্তকরণ থেকে লাইসেন্স পর্যন্ত ধাপে ধাপে পথ।",
  "certification.describe": "আপনার পণ্যের বর্ণনা দিন বা মান নম্বর লিখুন",
  "certification.analyze": "বিশ্লেষণ করুন",
  "certification.generateChecklist": "কমপ্লায়েন্স চেকলিস্ট তৈরি করুন",
  "certification.documents": "প্রয়োজনীয় নথি",
  "certification.notes": "গুরুত্বপূর্ণ টীকা",
  "certification.schemes": "সার্টিফিকেশন স্কিম",

  "checklist.title": "পণ্য কমপ্লায়েন্স চেকলিস্ট",
  "checklist.subtitle": "সার্টিফিকেশনের দিকে আপনার অগ্রগতি দেখুন।",
  "checklist.completed": "সম্পন্ন",
  "checklist.generate": "চেকলিস্ট তৈরি করুন",
  "checklist.product": "পণ্য",
  "checklist.reset": "অগ্রগতি রিসেট করুন",

  "labs.title": "পরীক্ষাগার খুঁজুন",
  "labs.subtitle": "পণ্য, মান, পরীক্ষার ধরন ও অবস্থান অনুযায়ী স্বীকৃত পরীক্ষাগার ছাঁকুন।",
  "labs.state": "রাজ্য",
  "labs.city": "শহর",
  "labs.testType": "পরীক্ষার ধরন",
  "labs.standard": "মান",
  "labs.category": "পণ্য শ্রেণি",
  "labs.capabilities": "পরীক্ষার সক্ষমতা",
  "labs.scope": "স্বীকৃত পরিধি",
  "labs.recognition": "স্বীকৃতির অবস্থা",
  "labs.contact": "যোগাযোগ",
  "labs.noFabrication":
    "এখানে দেখানো পরীক্ষাগারের তথ্য কেবল লোড করা ডেটাসেট থেকে। এই পৃষ্ঠার কিছুই AI দ্বারা তৈরি নয়।",

  "hallmarking.title": "হলমার্কিং সহকারী",
  "hallmarking.subtitle": "সোনা, রুপা, HUID, হলমার্কিং কেন্দ্র ও ভোক্তা যাচাই।",
  "hallmarking.ask": "হলমার্কিং সম্পর্কে জিজ্ঞাসা করুন…",

  "consumer.title": "BIS ভোক্তা সহকারী",
  "consumer.subtitle": "চিহ্ন, যাচাই, নিরাপত্তা ও অভিযোগ নিয়ে সহজ ভাষায় সহায়তা।",
  "consumer.ask": "সহজ কথায় জিজ্ঞাসা করুন…",

  "admin.title": "জ্ঞানভাণ্ডার প্রশাসন",
  "admin.totalStandards": "মোট মান",
  "admin.indexedDocuments": "সূচিবদ্ধ নথি",
  "admin.indexedChunks": "সূচিবদ্ধ খণ্ড",
  "admin.certificationDocs": "সার্টিফিকেশন স্কিম",
  "admin.labRecords": "পরীক্ষাগার রেকর্ড",
  "admin.hallmarkingDocs": "হলমার্কিং বিষয়",
  "admin.lastUpdate": "সর্বশেষ জ্ঞান হালনাগাদ",
  "admin.upload": "BIS নথি আপলোড করুন",
  "admin.uploadHint": "PDF, TXT বা Markdown, ৪০ MB পর্যন্ত। নথিটি সঙ্গে সঙ্গে সূচিবদ্ধ হয়।",
  "admin.documents": "নথি",
  "admin.failed": "ব্যর্থ / আংশিক নথি",
  "admin.queries": "প্রশ্ন লগ",
  "admin.quality": "পুনরুদ্ধারের গুণমান",
  "admin.reindex": "সূচি পুনর্নির্মাণ",
  "admin.remove": "সরান",
  "admin.signInRequired": "জ্ঞানভাণ্ডার পরিচালনার জন্য প্রশাসক অ্যাকাউন্টে সাইন ইন করুন।",

  "login.title": "সাইন ইন",
  "login.subtitle": "জ্ঞানভাণ্ডার পরিচালনার জন্য প্রশাসক অ্যাক্সেস প্রয়োজন।",
  "login.username": "ব্যবহারকারীর নাম",
  "login.password": "পাসওয়ার্ড",
  "login.submit": "সাইন ইন",
  "login.demoCredentials": "ডেমো শংসাপত্র",

  "about.title": "এই সহকারী সম্পর্কে",

  "demo.banner":
    "ডেমো ডেটা — উৎপাদনের আগে অনুমোদিত BIS ডেটা দিয়ে প্রতিস্থাপন করুন। এখানে লোড করা রেকর্ড উদাহরণমাত্র, সরকারি BIS নির্যাস নয়।",
  "footer.disclaimer":
    "এটি একটি AI সিদ্ধান্ত-সহায়ক প্রোটোটাইপ। এটি সার্টিফিকেশন দেয় না এবং কোনো সরকারি BIS পরিষেবা নয়। সর্বদা সরকারি BIS উৎসের সঙ্গে যাচাই করুন।",
};

const DICTIONARIES: Record<Language, Record<TranslationKey, string>> = {
  en: en as unknown as Record<TranslationKey, string>,
  hi,
  bn,
};

interface I18nValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem("bis_language") as Language | null;
      if (stored && stored in DICTIONARIES) setLanguageState(stored);
    } catch {
      /* private mode or storage disabled - the English default is fine */
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    try {
      window.localStorage.setItem("bis_language", lang);
    } catch {
      /* non-fatal */
    }
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback(
    (key: TranslationKey) => DICTIONARIES[language][key] ?? DICTIONARIES.en[key] ?? key,
    [language],
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used inside <I18nProvider>");
  return ctx;
}
